/**
* Blog Types
*/
const LOAD_AUTH_SUCCESS = 'LOAD_AUTH_SUCCESS';
const LOAD_AUTH_LOGOUT = 'LOAD_AUTH_LOGOUT';
const LOAD_PRODUCTS = 'LOAD_PRODUCTS';

module.exports = {
    LOAD_AUTH_SUCCESS,
    LOAD_AUTH_LOGOUT,
    LOAD_PRODUCTS
}